version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:18.20.4-browsers

jobs:
  build:
    docker:
      - image: cimg/node:18.20.4-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install Angular
          command: sudo npm install -g @angular/cli
      - run:
          name: Install Dependencies
          command: npm ci --legacy-peer-deps
      - run:
          name: Install Chrome and Firefox
          command: |
            sudo apt-get update -y
            sudo apt-get install -y wget gnupg2
            # Install Chrome
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
            sudo apt-get update -y
            sudo apt-get install -y google-chrome-stable
            # Install Firefox
            sudo apt-get install -y firefox
      - run:
          name: Build Ionic App for Web
          command: npm run build
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - www

  deploy:
    docker:
      - image: cimg/node:18.20.4-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Deploy to GitHub Pages
          command: |
            git config --global user.email "debanilguha86@gmail.com"
            git config --global user.name "Debanil1986"

            sudo npm install -g gh-pages


            npx gh-pages -d www -r https://$GH_TOKEN@github.com/Debanil1986/SalaryChecker.git
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
